<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AsblDocumentCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsblDocumentCatRepository extends EntityRepository{

    public function getByMember(){
        $query = $this->_em->createQuery('SELECT f FROM SERCOMAppBundle:AsblDocumentCat f JOIN f.sitegroup s WHERE s.name LIKE ?1 ')
            ->setParameter(1,"ROLE_MEMBRE" );
        return $query->getResult();
    }

    public function getByComite(){
        $query = $this->_em->createQuery('SELECT f FROM SERCOMAppBundle:AsblDocumentCat f JOIN f.sitegroup s WHERE s.name LIKE ?1 ')
            ->setParameter(1,"ROLE_COMITE" );
        return $query->getResult();
    }

    public function getByAnimateur(){
        $query = $this->_em->createQuery('SELECT f FROM SERCOMAppBundle:AsblDocumentCat f JOIN f.sitegroup s WHERE s.name LIKE ?1 ')
            ->setParameter(1,"ROLE_ANIMATEUR" );
        return $query->getResult();
    }

    public function getByPresident(){
        $query = $this->_em->createQuery('SELECT f FROM SERCOMAppBundle:AsblDocumentCat f ');
        return $query->getResult();
    }

    public function getByRole($role){
        $result = array();
        if ( $role == 'ROLE_MEMBRE'){
            $result = array_merge($this->getByMember());
        }
        if ( $role == 'ROLE_COMITE'){
            $result = array_merge($this->getByMember(), $this->getByComite());
        }
        if ( $role == 'ROLE_ANIMATEUR'){
            $result = array_merge($this->getByMember(), $this->getByComite(),$this->getByAnimateur() );
        }
        if ( $role == 'ROLE_PRESIDENT'){
            $result = $this->getByPresident();
        }
        return $result;

    }
}
