<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AsblDocumentSousCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsblDocumentSousCatRepository extends EntityRepository{

    public function findByCat($id){
        $query = $this->createQueryBuilder('t')->where('t.category = ?1')->setParameter(1, $id)->getQuery()->getArrayResult();
        return $query;
    }

}
