<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachementRepository extends EntityRepository{

    public function isInboxFileGranted($attach_id, $person_id){
        $query = $this->_em->createQuery('SELECT a FROM SERCOMAppBundle:Attachement a JOIN a.privatemessage mp JOIN mp.receivers r JOIN r.member m JOIN m.person p WHERE
              a = ?1 AND p = ?2')->setParameters(array(1 => $attach_id, 2 => $person_id));
        return $query->getResult();
    }

    public function isOutboxFileGranted($attach_id, $person_id){
        $query = $this->_em->createQuery('SELECT a FROM SERCOMAppBundle:Attachement a JOIN a.privatemessage mp JOIN mp.sender m JOIN m.person p WHERE
              a = ?1 AND p = ?2')->setParameters(array(1 => $attach_id, 2 => $person_id));
        return $query->getResult();
    }

}
