<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends EntityRepository{

    public function findClasses($page = 1, $maxperpage = 10){
        $query = $this->_em->createQueryBuilder()->select('m')->from('SERCOMAppBundle:Classe','m');

        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($query);
    }

    public function countClasses(){
        $query = $this->_em->createQuery('SELECT COUNT(m) FROM SERCOMAppBundle:Classe m');
        return $query->getSingleScalarResult();
    }

    public function search($search){
        $query1 = $this->_em->createQuery('SELECT DISTINCT p FROM SERCOMAppBundle:Student p JOIN p.person m WHERE m.lastname LIKE ?1 ')
            ->setParameter(1, '%'.$search.'%');

        $query2 = $this->_em->createQuery('SELECT DISTINCT p FROM SERCOMAppBundle:Student p JOIN p.person m WHERE  m.firstname LIKE ?1 ')
            ->setParameter(1, '%'.$search.'%');


        $res = array();
        foreach ( $query1->getResult() as $p){
            if ( !in_array($p, $res)){
                array_push($res, $p);
            }
        }
        foreach ( $query2->getResult() as $p){
            if ( !in_array($p, $res)){
                array_push($res, $p);
            }
        }

        return $res;
    }
}
