<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoursePlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursePlanningRepository extends EntityRepository{

    public function getCal(){
        $query = $this->_em->createQuery('SELECT e FROM SERCOMAppBundle:CoursePlanning e');
        return $query->getResult();
    }

    public function findEvent($d, $title){
        $query = $this->_em->createQueryBuilder()->select('c')
            ->from('SERCOMAppBundle:CoursePlanning','c')
            ->join('c.classe','cl')
            ->where('cl.name LIKE ?1 and c.datecours = ?2')
            ->setParameters(array(1 => $title, 2 => $d));

        return $query->getQuery()->getSingleResult();
    }

    public function findLastEventClasse( $student){
        $query = $this->_em->createQueryBuilder()->select('p')
            ->from('SERCOMAppBundle:CoursePlanning','p')
            ->join('p.classe','c')
            ->join('c.students','s')
            ->where('s.person = ?2 AND p.datecours > ?1')
            ->addOrderBy('p.datecours', 'ASC')->setParameters(array(1 => new \DateTime(), 2 => $student));
        return $query->getQuery()->getSingleResult();
    }
}
