<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository{

    public function getCal(){
        $query = $this->_em->createQuery('SELECT e FROM SERCOMAppBundle:Event e WHERE e.validate = 1');
        return $query->getResult();
    }

    public function getLastEven(){
        $query = $this->_em->createQuery('SELECT e FROM SERCOMAppBundle:Event e WHERE e.validate = 1 AND e.dateHourEvent > ?1 ORDER BY e.dateHourEvent DESC')
            ->setParameter(1, new \DateTime());
        return $query->getResult();
    }

    public function getAgenda(){
        $query = $this->_em->createQueryBuilder()->select('p')
            ->from('SERCOMAppBundle:Event','p')
            ->where('p.validate = 1 and p.dateHourEvent > ?1')
            ->addOrderBy('p.dateHourEvent', 'ASC')
            ->setParameter(1, new \DateTime())
            ->setMaxResults(2);
        return $query->getQuery()->getResult();
    }
}
