<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository{

    public function getCal(){
        $query = $this->_em->createQuery('SELECT e FROM SERCOMAppBundle:Event e WHERE e.validate = 1');
        return $query->getResult();
    }
}
