<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use SERCOM\AppBundle\Entity\Forum;
use PDO;


/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository{

    public function getCountForumTopics(Forum $forum){
        $sql = "SELECT COUNT(*) FROM forum_topic WHERE forum_id = ?";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue(1, $forum->getForumId(), PDO::PARAM_INT );
        $stmt->execute();
        return $stmt->fetch();
    }

    public function getOrdererPosts(Forum $forum){
        $sql = "SELECT * FROM forum_post JOIN forum_topic ON forum_topic.topic_id = forum_post.topic_id JOIN forum ON forum_topic.forum_id = forum.forum_id WHERE forum.forum_id = ? ORDER BY forum_post.datepost ASC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue(1, $forum->getForumId());
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function getForums($member){

        $query = $this->_em->createQuery('SELECT DISTINCT f FROM SERCOMAppBundle:Forum f JOIN f.forumgroups g JOIN g.members m JOIN m.person p WHERE p.person_id = ?1 ')
            ->setParameter(1, $member->getPerson()->getPersonid());
        return $query->getResult();
    }

}
