<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ForumTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumTopicRepository extends EntityRepository{

    public function countPosts($topic){
        $sql = "SELECT COUNT(*) FROM forum_post WHERE topic_id = ? ";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue(1, $topic);
        $stmt->execute();
        return $stmt->fetch();
    }

    public function getLastPost($topic){
        $sql = "SELECT distinct(post_id) from forum_post WHERE topic_id = ? ORDER BY forum_post.datepost DESC LIMIT 1";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue(1, $topic);
        $stmt->execute();
        return $stmt->fetch();
    }


    public function getOrderedTopics($forum, $priority){
        $sql = "SELECT distinct(forum_post.topic_id) from forum_post JOIN forum_topic ON forum_topic.topic_id = forum_post.topic_id WHERE forum_topic.forum_id = ? AND forum_topic.priority = ? ORDER BY forum_post.datepost DESC";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue(1, $forum);
        $stmt->bindValue(2, $priority);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function getLastPosts($forum, $prio){
        $query = $this->_em->createQuery('SELECT t FROM SERCOMAppBundle:ForumTopic t JOIN t.forumposts p JOIN t.forum f WHERE f.forum_id = ?1 AND t.priority = ?2 ORDER BY p.datePost DESC')
            ->setParameters(array( 1 => $forum, 2 => $prio));
        return $query->getResult();
    }

    public function countTopics($forum){
        $query = $this->_em->createQuery('SELECT COUNT(t.topic_id) FROM SERCOMAppBundle:ForumTopic t WHERE t.forum = ?1')
            ->setParameter( 1 , $forum);
        return $query->getScalarResult();
    }


}

