<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository{

    public function getMembers($id, $idevent){

        $query = $this->_em->createQuery('SELECT DISTINCT u FROM SERCOMAppBundle:Member u JOIN u.dateproposals d JOIN d.events e WHERE u.person != ?2 AND e.event_id = ?1 ORDER BY d.datehour ASC')
                            ->setParameters(array( 1 => $idevent, 2 => $id));
        return $query->getResult();
    }

    public function getAllMembers($idevent){

        $query = $this->_em->createQuery('SELECT DISTINCT u FROM SERCOMAppBundle:Member u JOIN u.dateproposals d JOIN d.events e WHERE e.event_id = ?1 ORDER BY d.datehour ASC')
            ->setParameter( 1 , $idevent);
        return $query->getResult();
    }
}
