<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReceiveMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiveMessageRepository extends EntityRepository{

    public function getMessages($id){
        $query = $this->_em->createQuery('SELECT r FROM SERCOMAppBundle:ReceiveMessage r JOIN r.privatemessages m WHERE r.member = ?1 AND r.message_delete = 0 ORDER BY m.dateMessage DESC')
            ->setParameter(1, $id);
        return $query->getResult();
    }

    public function getMessage($id, $member){
        $query = $this->_em->createQuery('SELECT r FROM SERCOMAppBundle:ReceiveMessage r JOIN r.privatemessages p WHERE r.privatemessages = ?1 AND r.member = ?2 ')
            ->setParameters(array(1 => $id, 2 => $member));
        return $query->getResult();
    }

    public function getDeletedMessage($mp_id){
        $query = $this->_em->createQuery('SELECT r FROM SERCOMAppBundle:ReceiveMessage r WHERE r.privatemessages = ?1 AND r.message_delete = 1 ')
            ->setParameter( 1 , $mp_id);
        return $query->getResult();
    }
}
