<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use SERCOM\AppBundle\articles\Article;

/**
 * SiteArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteArticleRepository extends EntityRepository{

    public function getBySection($section){
        $query = $this->_em->createQueryBuilder()->select('a')
            ->from('SERCOMAppBundle:SiteArticle','a')
            ->join('a.sitesection','s')
            ->where('s.name LIKE ?1')
            ->orderBy('a.publishDate', 'DESC')
            ->setParameter(1, $section);
        return $query->getQuery()->getResult();

    }

    public function getLastArticles(){
        $query = $this->_em->createQueryBuilder()->select('a')
            ->from('SERCOMAppBundle:SiteArticle','a')
            ->where('a.publish = 1')
            ->orderBy('a.publishDate', 'DESC')
            ->setMaxResults(5);
        $tab = $query->getQuery()->getResult();
        $res = array();
        foreach( $tab as $art){
            $a = new Article($art);
            array_push($res,$a);
        }
        return $res;
    }

}
