<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteArticleRepository extends EntityRepository{

    public function getBySection($section){
        $query = $this->_em->createQueryBuilder()->select('a')
            ->from('SERCOMAppBundle:SiteArticle','a')
            ->join('a.sitesection','s')
            ->where('s.name LIKE ?1')
            ->orderBy('a.publishDate', 'DESC')
            ->setParameter(1, $section);
        return $query->getQuery()->getResult();

    }

}
