<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository{

    public function autocomplete($tag){
        $query = $this->_em->createQuery('SELECT t FROM SERCOMAppBundle:Tag t WHERE t.tagName LIKE ?1')->setParameter(1, '%'.$tag.'%');
        return $query->getResult();

    }


}
