<?php

namespace SERCOM\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends EntityRepository{

    public function findTeachers($page = 1, $maxperpage = 10){
        $query = $this->_em->createQueryBuilder()->select('m')->from('SERCOMAppBundle:Teacher','m')->join('m.person','p')->where('p.validate = 1 and m.actif = 1');

        $query->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($query);
    }

    public function countTeachers(){
        $query = $this->_em->createQueryBuilder()->select('m')->from('SERCOMAppBundle:Teacher','m')->join('m.person','p')->where('p.validate = 1 and m.actif = 1');
        return count($query->getQuery()->getResult());
    }

    public function search($search){

        $query = $this->_em->createQueryBuilder()->select('t')
                            ->from('SERCOMAppBundle:Teacher','t')
                            ->join('t.person','p')
                            ->join('t.classes','c')
                            ->join('c.suject','s')
                            ->where('p.lastname LIKE ?1 OR p.firstname LIKE ?2 OR c.name LIKE ?3 AND t.actif = 1 OR s.name LIKE ?4')
                            ->groupBy('t')
                            ->setParameters(array(1 => '%'.$search.'%' , 2 => '%'.$search.'%', 3 => '%'.$search.'%', 4 => '%'.$search.'%' ));

        return $query->getQuery()->getResult();
    }
}
